site:
    title: cwen's blog
    introduce: 沉稳，不乏可爱
    limit: 10
    theme: "themes/default"
    url: http://int64.me
    comment: int64
    github: "https://github.com/cwen-coder"
    facebook:
    twitter:
serve:
    addr: "localhost:3000"

publish:
    cmd: |
        git add -A
        git commit -m "update"
        git push origin

