site:
    title: cwen
    introduce: Life is magic. Coding is art.
    limit: 10
    theme: "themes/default"
    url: http://int64.me
    comment: int64
    github: "https://github.com/cwen0"
    facebook: "https://www.facebook.com/cwen.yin"
    twitter: "https://twitter.com/CWenYin"
serve:
    addr: "localhost:3000"

publish:
    cmd: |
        git add -A
        git commit -m "update"
        git push origin

